import { getExerciseProgress } from './progression';
import { calculateRecovery } from './recovery';

export function buildWeeklyReport({ profile={}, weightLogs=[], workoutLogs=[], foodLogs=[], sleepLogs=[], waterLogs=[], weekOffset=0 }={}) {
  const now=new Date(); now.setDate(now.getDate() - weekOffset*7); const since=new Date(now); since.setDate(now.getDate()-6); const key=d=>String(d.date).slice(0,10); const inWeek=l=>{const d=new Date(key(l)); return d>=new Date(since.toDateString()) && d<=now;};
  const w=workoutLogs.filter(inWeek), f=foodLogs.filter(inWeek), s=sleepLogs.filter(inWeek).filter(x=>x.sleepType==='night'||!x.sleepType), water=waterLogs.filter(inWeek);
  const days=[...new Set(w.map(key))]; const byDay=(logs,field)=>{const m={}; logs.forEach(l=>{const d=key(l);m[d]=(m[d]||0)+(Number(l[field])||0)});return m};
  const cal=byDay(f,'calories'), prot=byDay(f,'protein'), carbs=byDay(f,'carbs'), fats=byDay(f,'fats'), waterDay=byDay(water,'amountMl');
  const avg=o=>{const v=Object.values(o);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0}; const sleepVals=s.map(x=>Number(x.duration)||0).filter(Boolean);
  const muscles={}; w.forEach(x=>{const m=x.muscleGroup||'Other';muscles[m]=(muscles[m]||0)+1}); const mostTrained=Object.entries(muscles).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';
  const prs=[]; const names=[...new Set(w.map(x=>x.exerciseName).filter(Boolean))]; names.forEach(n=>{const all=getExerciseProgress(workoutLogs,n); const week=getExerciseProgress(w,n); if(week.bestWeight>0 && week.bestWeight>=all.bestWeight) prs.push({exercise:n,weight:week.bestWeight});});
  const recoveryDays=[]; for(let i=0;i<7;i++){const d=new Date(now);d.setDate(now.getDate()-i);const ds=d.toISOString().slice(0,10);const rec=calculateRecovery({profile,sleepLogs:sleepLogs.filter(x=>String(x.date).slice(0,10)<=ds),foodLogs:foodLogs.filter(x=>String(x.date).slice(0,10)<=ds),waterLogs:waterLogs.filter(x=>String(x.date).slice(0,10)<=ds),workoutLogs:workoutLogs.filter(x=>String(x.date).slice(0,10)<=ds),asOf:d}); if(rec.available) recoveryDays.push({date:ds,score:rec.score});}
  const recAvg=recoveryDays.length?Math.round(avg(Object.fromEntries(recoveryDays.map(x=>[x.date,x.score])))):null;
  const bestRec=recoveryDays.slice().sort((a,b)=>b.score-a.score)[0], lowRec=recoveryDays.slice().sort((a,b)=>a.score-b.score)[0];
  const startW=[...weightLogs].filter(inWeek).sort((a,b)=>String(a.date).localeCompare(String(b.date)))[0]?.weight; const currentW=[...weightLogs].filter(inWeek).sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0]?.weight;
  return { workout:{days:days.length,target:Number(profile.workoutTarget)||4,exercises:w.length,mostTrained,trend:days.length-(Number(profile.workoutTarget)||4)}, nutrition:{avgCalories:Math.round(avg(cal)),target:Number(profile.calorieTarget)||2300,avgProtein:Math.round(avg(prot)),proteinTarget:Number(profile.proteinTarget)||140,avgCarbs:Math.round(avg(carbs)),avgFat:Math.round(avg(fats)),calorieDays:Object.values(cal).filter(v=>v>=((Number(profile.calorieTarget)||2300)*.9)&&v<=((Number(profile.calorieTarget)||2300)*1.15)).length,proteinDays:Object.values(prot).filter(v=>v>=Number(profile.proteinTarget||140)).length}, sleep:{avg:sleepVals.length?sleepVals.reduce((a,b)=>a+b,0)/sleepVals.length:0,target:Number(profile.sleepTarget)||8,nights:sleepVals.filter(v=>v>=Number(profile.sleepTarget||8)).length,best:sleepVals.length?Math.max(...sleepVals):0,worst:sleepVals.length?Math.min(...sleepVals):0}, water:{avgMl:Math.round(avg(waterDay)),targetMl:Number(profile.waterTargetMl)||2500,days:Object.values(waterDay).filter(v=>v>=Number(profile.waterTargetMl||2500)).length}, weight:{start:startW??null,current:currentW??null,change:startW!=null&&currentW!=null?currentW-startW:null}, recovery:{average:recAvg,best:bestRec?.score??null,bestDate:bestRec?.date,lowest:lowRec?.score??null,lowestDate:lowRec?.date}, prs:prs.slice(0,10), overall:Math.round(((Math.min(100,(days.length/(Number(profile.workoutTarget)||4))*100))+ (Math.min(100,(avg(prot)/(Number(profile.proteinTarget)||140))*100)) + (sleepVals.length?Math.min(100,(avg({x:sleepVals.reduce((a,b)=>a+b,0)})/sleepVals.length)/(Number(profile.sleepTarget)||8)*100):0) + (Object.values(waterDay).length?Math.min(100,(avg(waterDay)/(Number(profile.waterTargetMl)||2500))*100):0))/4)};
}